services:
  postgres:
    image: postgres:16-alpine
    container_name: beeconnectlab-postgres
    restart: unless-stopped
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: beeconnect
      POSTGRES_PASSWORD: beeconnect
      POSTGRES_DB: beeconnectlab
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
